"""add state_origin to company models and api/upload.py

Revision ID: 113f885975b5
Revises: b3138cecf7d8
Create Date: 2026-04-30 11:17:48.134726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113f885975b5'
down_revision: Union[str, None] = 'b3138cecf7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('state_origin', sa.String(length=2), nullable=True))
    op.add_column('items_order', sa.Column('external_item_id', sa.String(length=50), nullable=True))
    op.drop_constraint('fk_user_company_id', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_company_id', 'user', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items_order', 'external_item_id')
    op.drop_column('company', 'state_origin')
    # ### end Alembic commands ###
