"""add regimetributario to company and change all empresa.py files to company.py

Revision ID: 6ec006f331aa
Revises: 113f885975b5
Create Date: 2026-04-30 12:47:29.380136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec006f331aa'
down_revision: Union[str, None] = '113f885975b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('regime_tributario', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'regime_tributario')
    # ### end Alembic commands ###
